# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12

  monitor_services:
    class: MonitorServicesJob
    queue: default
    schedule: every hour

  nightly_transcribe:
    class: NightlyTranscribeJob
    queue: default
    schedule: every day at 2am

  fotheidil_fixer:
    class: FotheidilFixerJob
    queue: default
    schedule: every 2 hours

  process_voice_recording_entry:
    class: ProcessVoiceRecordingEntryJob
    queue: default
    schedule: every minute

development:
  # nightly_transcribe:
  #   class: NightlyTranscribeJob
  #   queue: default
  #   schedule: every 6 hours

  # fotheidil_fixer:
  #   class: FotheidilFixerJob
  #   queue: default
  #   schedule: every hour
